Repository imi-frankfurt/dataelementhub.model, pull requests merged in 2022-06, with the labels that each got.

#66 #65 - Enable releasing elements using update controller
  src/main/java/de/dataelementhub/model/handler/element/DataElementGroupHandler.java
  src/main/java/de/dataelementhub/model/handler/element/DataElementHandler.java
  src/main/java/de/dataelementhub/model/handler/element/RecordHandler.java
  src/main/java/de/dataelementhub/model/handler/element/section/ValueDomainHandler.java
  src/main/java/de/dataelementhub/model/handler/element/section/validation/PermittedValueHandler.java
  src/main/java/de/dataelementhub/model/service/ElementService.java
Labels: feature, needs review

#68 #67 - Search function is not working for namespaces
  src/main/java/de/dataelementhub/model/service/SearchService.java
Labels: bug, needs review

#70 #69 - Don't allow released dataelementgroups with draft dataelements
  src/main/java/de/dataelementhub/model/handler/element/DataElementGroupHandler.java
  src/main/java/de/dataelementhub/model/handler/element/RecordHandler.java
Labels: bug, needs review

#79 #78 - Updating drafts is not working properly
  src/main/java/de/dataelementhub/model/handler/element/DataElementGroupHandler.java
  src/main/java/de/dataelementhub/model/handler/element/DataElementHandler.java
  src/main/java/de/dataelementhub/model/handler/element/RecordHandler.java
  src/main/java/de/dataelementhub/model/handler/element/section/MemberHandler.java
Labels: bug

#73 #59 - updating namespaces causes issues in namespace access table
  src/main/java/de/dataelementhub/model/handler/AccessLevelHandler.java
Labels: bug, critical, needs review

#72 #71 - fix update members for all parent elements
  src/main/java/de/dataelementhub/model/handler/element/DataElementGroupHandler.java
  src/main/java/de/dataelementhub/model/handler/element/RecordHandler.java
Labels: bug, needs review

#84 #83 - Creating a dataElement with valueDomainUrn that does not exist leads to 500 internal server error
  src/main/java/de/dataelementhub/model/handler/element/DataElementHandler.java
Labels: bug, needs review

#82 #46 - Released enumeratedValueDomains should have at least one permitted value
  src/main/java/de/dataelementhub/model/handler/element/section/ValueDomainHandler.java
Labels: bug, needs review

#86 #85 - Released valueDomain is a requirement for releasing a dataElement
  src/main/java/de/dataelementhub/model/handler/element/DataElementHandler.java
  src/main/java/de/dataelementhub/model/handler/element/section/IdentificationHandler.java
  src/main/java/de/dataelementhub/model/service/ElementService.java
  src/main/java/de/dataelementhub/model/service/NamespaceService.java
Labels: bug, needs review
