Repository imi-frankfurt/dataelementhub.model, pull requests merged in 2022-05, with the labels that each got.

#41 #32 - Importing the same valueDomain twice leads to internal server error
  src/main/java/de/dataelementhub/model/handler/element/DataElementHandler.java
  src/main/java/de/dataelementhub/model/handler/element/section/IdentificationHandler.java
  src/main/java/de/dataelementhub/model/handler/element/section/validation/PermittedValuesHandler.java
Labels: bug, needs review

#39 #38 - Reconstruct export output and import input
  pom.xml
  src/main/java/de/dataelementhub/model/adapter/NumericValidationAdapter.java
  src/main/java/de/dataelementhub/model/dto/element/StagedElement.java
  src/main/java/de/dataelementhub/model/dto/importexport/ExportInfo.java
  src/main/java/de/dataelementhub/model/dto/importexport/ExportRequest.java
  src/main/java/de/dataelementhub/model/dto/importexport/ImportExport.java
  src/main/java/de/dataelementhub/model/dto/importexport/ImportInfo.java
  src/main/java/de/dataelementhub/model/dto/listviews/StagedElement.java
  src/main/java/de/dataelementhub/model/handler/element/RecordHandler.java
  src/main/java/de/dataelementhub/model/handler/element/section/MemberHandler.java
  src/main/java/de/dataelementhub/model/handler/export/ExportHandler.java
  src/main/java/de/dataelementhub/model/handler/importhandler/ImportHandler.java
  src/main/java/de/dataelementhub/model/service/ExportService.java
  src/main/java/de/dataelementhub/model/service/ImportService.java
Labels: needs review, refactoring

#43 #42 - Improve performance
  src/main/java/de/dataelementhub/model/DaoUtil.java
  src/main/java/de/dataelementhub/model/handler/UserHandler.java
  src/main/java/de/dataelementhub/model/handler/element/DataElementGroupHandler.java
  src/main/java/de/dataelementhub/model/handler/element/DataElementHandler.java
  src/main/java/de/dataelementhub/model/handler/element/ElementHandler.java
  src/main/java/de/dataelementhub/model/handler/element/ElementPathHandler.java
  src/main/java/de/dataelementhub/model/handler/element/NamespaceHandler.java
  src/main/java/de/dataelementhub/model/handler/element/RecordHandler.java
  src/main/java/de/dataelementhub/model/handler/element/section/ConceptAssociationHandler.java
  src/main/java/de/dataelementhub/model/handler/element/section/IdentificationHandler.java
  src/main/java/de/dataelementhub/model/handler/element/section/MemberHandler.java
  src/main/java/de/dataelementhub/model/handler/element/section/SlotHandler.java
  src/main/java/de/dataelementhub/model/handler/element/section/ValueDomainHandler.java
  src/main/java/de/dataelementhub/model/handler/element/section/validation/PermittedValueHandler.java
  src/main/java/de/dataelementhub/model/handler/element/section/validation/PermittedValuesHandler.java
  src/main/java/de/dataelementhub/model/handler/export/ExportHandler.java
  src/main/java/de/dataelementhub/model/handler/export/StagedElementHandler.java
  src/main/java/de/dataelementhub/model/handler/importhandler/ImportHandler.java
  src/main/java/de/dataelementhub/model/handler/importhandler/StagedElementHandler.java
  src/main/java/de/dataelementhub/model/service/ElementRelationService.java
  src/main/java/de/dataelementhub/model/service/ElementService.java
  src/main/java/de/dataelementhub/model/service/ExportService.java
  src/main/java/de/dataelementhub/model/service/ImportService.java
  src/main/java/de/dataelementhub/model/service/NamespaceService.java
  src/main/java/de/dataelementhub/model/service/SearchService.java
  src/main/java/de/dataelementhub/model/service/SourceService.java
  src/main/java/de/dataelementhub/model/service/UserService.java
Labels: needs review, refactoring

#45 #44 - enable calling path for public elements without login
  src/main/java/de/dataelementhub/model/handler/element/ElementPathHandler.java
  src/main/java/de/dataelementhub/model/handler/element/NamespaceHandler.java
  src/main/java/de/dataelementhub/model/handler/element/RecordHandler.java
Labels: feature, needs review

#52 #51 unauthorized access to elements in hidden namespaces must be denied
  src/main/java/de/dataelementhub/model/handler/element/NamespaceHandler.java
  src/main/java/de/dataelementhub/model/service/ElementService.java
Labels: bug, critical, needs review

#56 #53 - Do not keep identification for permitted values when creating a value domain
  src/main/java/de/dataelementhub/model/handler/element/section/ValueDomainHandler.java
Labels: bug, needs review

#57 #54 - Importing enumerated value domain does not import permitted values
  src/main/java/de/dataelementhub/model/handler/element/ElementHandler.java
Labels: bug, needs review

#62 #61 - Namespace members are not returned after updating the namespace
  src/main/java/de/dataelementhub/model/handler/element/NamespaceHandler.java
Labels: bug, needs review

#64 #63 - Retrieving path of an element does not return full path
  src/main/java/de/dataelementhub/model/handler/element/ElementPathHandler.java
Labels: bug, needs review
